#!/bin/sh
mkdir /opt/arma3/server -p
mkdir /opt/arma3/profiles -p
mkdir /data/profiles

if [ ! -f /opt/arma3/server/arma3server ]; then
	/opt/steam/steamcmd \
		+@NoPromptForPassword 1 \
		+@ShutdownOnFailedCommand 1 \
		+login ${STEAM_USER} ${STEAM_PASS} \
		+force_install_dir /opt/arma3/server \
		+app_update ${STEAM_APPID} validate \
		+quit
fi
