#!/bin/bash
POSTGRESQL_USER=${POSTGRESQL_USER:-"docker"}
POSTGRESQL_PASS=${POSTGRESQL_PASS:-"docker"}
POSTGRESQL_DB=${POSTGRESQL_DB:-"docker"}
if [ ! "$(ls -A /data)" ]; then
	su postgres -c "initdb -D /data"
	su postgres -c "psql -c \"CREATE USER $POSTGRESQL_USER WITH SUPERUSER PASSWORD '$POSTGRESQL_PASS';\""
	su postgres -c "createdb -O $POSTGRESQL_USER $POSTGRESQL_DB"
fi
chown -R postgres:postgres /data
