FROM maxexcloo/arma3

MAINTAINER Zenobius Jiricek <airtonix@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# TODO: wget epoch server files
# TODO: link to mysql db
# TODO: discover errors due to assumptions