#!/bin/bash
[ -f /config/init ] && bash /config/init
if tty -s; then
	supervisord
	while true; do
		echo "Exit supervisorctl with Ctrl-D. Detach with Ctrl-P + Ctrl-Q."
		supervisorctl
		echo "Exit shell with Ctrl-D. Detach with Ctrl-P + Ctrl-Q."
		bash
	done
fi
supervisord -n
